name: docker_publish

on:
  push:
    branches:
      - 'chore/ci-publish-docker'
      - 'main'
      # TODO: remove temp branch
      - 'fix/circular-deps-finalized-head'
      - 'feat/simplify-range-finalized-check'
    tags:
      - '*'

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@v0.7.0
    with:
      run-build: true
      run-lint: true
      run-unit-tests: true
      run-check-mock-gen: true
      run-gosec: true
      gosec-args: "-exclude-generated -exclude-dir=testutil ./..."

  docker_pipeline:
    needs: ["lint_test"]
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@v0.7.0
    secrets: inherit
    with:
      publish: true
      repoName: finality-gadget